//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge11__DevPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidades
    {
        public int idtecnologia { get; set; }
        public string marca { get; set; }
        public int modelo { get; set; }
        public int año { get; set; }
        public double kilometros { get; set; }
        public double precio { get; set; }
    }
}
